/**
 * earthquakeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ordinates } from './ordinates';

export interface CoordinateSequence { 
    readonly dimension?: number;
    readonly measures?: number;
    readonly spatial?: number;
    ordinates?: Ordinates;
    readonly hasZ?: boolean;
    readonly hasM?: boolean;
    readonly zOrdinateIndex?: number;
    readonly mOrdinateIndex?: number;
    readonly count?: number;
}