/**
 * earthquakeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Dimension = 0 | 1 | 2 | -3 | -2 | -1;

export const Dimension = {
    NUMBER_0: 0 as Dimension,
    NUMBER_1: 1 as Dimension,
    NUMBER_2: 2 as Dimension,
    NUMBER_MINUS_3: -3 as Dimension,
    NUMBER_MINUS_2: -2 as Dimension,
    NUMBER_MINUS_1: -1 as Dimension
};