/**
 * earthquakeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';

export interface Envelope { 
    readonly isNull?: boolean;
    readonly width?: number;
    readonly height?: number;
    readonly minX?: number;
    readonly maxX?: number;
    readonly minY?: number;
    readonly maxY?: number;
    readonly area?: number;
    readonly minExtent?: number;
    readonly maxExtent?: number;
    centre?: Coordinate;
}