/**
 * earthquakeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Envelope } from './envelope';
import { Geometry } from './geometry';
import { IAttributesTable } from './iAttributesTable';

export interface IFeature { 
    geometry?: Geometry;
    boundingBox?: Envelope;
    attributes?: IAttributesTable;
}