/**
 * earthquakeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type OgcGeometryType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;

export const OgcGeometryType = {
    NUMBER_1: 1 as OgcGeometryType,
    NUMBER_2: 2 as OgcGeometryType,
    NUMBER_3: 3 as OgcGeometryType,
    NUMBER_4: 4 as OgcGeometryType,
    NUMBER_5: 5 as OgcGeometryType,
    NUMBER_6: 6 as OgcGeometryType,
    NUMBER_7: 7 as OgcGeometryType,
    NUMBER_8: 8 as OgcGeometryType,
    NUMBER_9: 9 as OgcGeometryType,
    NUMBER_10: 10 as OgcGeometryType,
    NUMBER_11: 11 as OgcGeometryType,
    NUMBER_12: 12 as OgcGeometryType,
    NUMBER_13: 13 as OgcGeometryType,
    NUMBER_14: 14 as OgcGeometryType,
    NUMBER_15: 15 as OgcGeometryType,
    NUMBER_16: 16 as OgcGeometryType
};