/**
 * earthquakeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { CoordinateSequence } from './coordinateSequence';
import { Dimension } from './dimension';
import { Envelope } from './envelope';
import { Geometry } from './geometry';
import { GeometryFactory } from './geometryFactory';
import { OgcGeometryType } from './ogcGeometryType';
import { PrecisionModel } from './precisionModel';

export interface Point { 
    factory?: GeometryFactory;
    userData?: any;
    srid?: number;
    precisionModel?: PrecisionModel;
    readonly numGeometries?: number;
    readonly isSimple?: boolean;
    readonly isValid?: boolean;
    readonly area?: number;
    readonly length?: number;
    centroid?: Point;
    interiorPoint?: Point;
    pointOnSurface?: Point;
    envelope?: Geometry;
    envelopeInternal?: Envelope;
    readonly isRectangle?: boolean;
    coordinateSequence?: CoordinateSequence;
    coordinates?: Array<Coordinate>;
    readonly numPoints?: number;
    readonly isEmpty?: boolean;
    dimension?: Dimension;
    boundaryDimension?: Dimension;
    x?: number;
    y?: number;
    coordinate?: Coordinate;
    readonly geometryType?: string;
    ogcGeometryType?: OgcGeometryType;
    boundary?: Geometry;
    z?: number;
    m?: number;
}